### ISSUE TITLE
Removal doesn't undo the activation thing

### ISSUE THREAD

**Issue by tonyg** [racket/readline-gpl#1]
So yesterday I fired up racket repl and was greeted with the warning that I wouldn't be getting any readline support. Fair enough. raco pkg install readline-gpl, and all is well.

Just now I wanted to see that warning again, so I raco pkg remove readline-gpl, and start up racket repl, only to be presented with
- no warning
- readline support

This doesn't seem quite right. Shouldn't removing the package put things back the way they were?
## To reproduce
- fresh racket on a fresh OS with minimal libs (e.g. no libeditline?) - sufficient to provoke the warning, at any rate
- racket repl should warn about no readline support
- raco pkg install readline-gpl
- racket should give readline support
- raco pkg remove readline-gpl
- no change: still readline support, no warning
## Expected

Warning after raco pkg remove readline-gpl; No readline support after raco pkg remove readline-gpl.

**Comment by samth** [comment]
cc @LeifAndersen @mflatt

**Comment by mflatt** [comment]
This is a bug in `raco setup`, and I've pushed a repair.
